kind: ConfigMap
apiVersion: v1
metadata:
  name: spring-db-config
data:
  DB_URL: jdbc:mysql://localhost:3306/dbs
  DB_DRIVER: com.mysql.cj.jdbc.Driver
  JPA_DIALECT: org.hibernate.dialect.MySQLDialect
  JPA_SHOW_SQL: "true"
  JPA_HBM2DDL_AUTO: update
