kind: ConfigMap
apiVersion: v1
metadata:
  name: spring-db-config
data:
  DB_URL: jdbc:mysql://springsql.mysql.database.azure.com:3306/dbs?useSSL=TRUE";
  DB_DRIVER: com.mysql.cj.jdbc.Driver
  JPA_DIALECT: org.hibernate.dialect.MySQLDialect
  JPA_SHOW_SQL: 'FALSE'
  JPA_HBM2DDL_AUTO: update
